### ISSUE TITLE
Check type is reference

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/protobuf-rules-gen#14]
Hi,
do you have an example on how I check if the type is a reference?

Or is this currently supported?

Thanks Dennis

P.S. I love this project, soooo awesome. I always wanted to start such a tool, but great that it already exists!

**Comment by rockwotj** [comment]
Currently you cannot. Protobuf doesn't have a type that really maps to a reference. Maybe if we had a special extension for a string type?

IE:

```
message Example {
  string ref = 2 [(google.firebase.rules.firebase_rules_field).reference_type = true];
}
```

Thoughts?

**Comment by IchordeDionysos** [comment]
That would do it, I think :)
