### ISSUE TITLE
Timestamp support

### ISSUE THREAD

**Issue by K0ff33** [firebase/protobuf-rules-gen#19]
`  // TODO(rockwotj): Support timestamps`

Timestamp support would be very much appreciated. At the moment it's one of the basic types missing.

**Comment by rockwotj** [comment]
WDYT about making this be the google.protobuf.Timestamp message?

This would end up being:

```
message Example {
  google.protobuf.Timestamp ts = 1;
}
```

Then this would end up being a check for `ts is timestamp`

**Comment by K0ff33** [comment]
Makes perfect sense to me.

**Comment by adamduren** [comment]
I'm interested in this library as well. Any progress here?

**Comment by rockwotj** [comment]
Have a PR open in #22

**Comment by rockwotj** [comment]
Created a new release for darwin with these changes. Should have a linux release done Monday when I'm at my Linux machine.
