### ISSUE TITLE
Multi type support (int32 or float)

### ISSUE THREAD

**Issue by K0ff33** [firebase/protobuf-rules-gen#20]
I'm wondering if it's possible to specify a property to have multiple accepted types. In my case I need to allow both int32 and float types because of the way how JS treats numbers in general.

When writing security rules manually I was doing a simple OR like:
`&& (resource.weight is float || resource.weight is int)`

But I guess that's not possible (yet) in the plugin?

**Comment by rockwotj** [comment]
I'm going to change `float` and `double` types in this plugin to allow for whole numbers as well.

**Comment by rockwotj** [comment]
BTW, you can just do `resource.weight is number` to get both
